#version: '3.9'
#services:

 # jaeger: #esse container tu dá o nome que quiser, aqui o professor tá chamando de jaeguer, jaeguer é feito em GO
  #  image: jaegertracing/all-in-one:latest
   # ports:
    #  - "16686:16686" # Jaeger UI porta padrão do Jaeguer
     # - "14268:14268" # Receive legacy OpenTracing traces, optional
      #- "4317:4317"   # OTLP gRPC receiver
     # - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      #- "14250:14250" # Receive from external otel-collector, optional
      #Jaeguer abre portas
    #environment:
     # - COLLECTOR_OTLP_ENABLED=true #executa o processo que roda as portas
      #imagem: mais ou menso classe do java
      #container: execuçãoda imagem
      #se anexar um sheel entra dentro do container
      #configuração para o jaeguer são 3>: dar nome apra o servico pra ele ifentificar que é um trace que faz parte do peimeiro, sebgnfo. terceiro serviço
version: '3.2'

services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # Use half of the available RAM
      discovery.type: "single-node" # Disable production mode
    networks:
      - graylog

  mongo:
    image: mongo:4.0
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.3.0 # graylog version
    ports:
      - "9000:9000" # HTTP
      - "12201:12201/udp" # GELF UDP
      - "1514:1514" # GELF TCP
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "forpasswordencryption"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    networks:
      - graylog
    depends_on:
      - elasticsearch
      - mongo

networks:
  graylog:
    driver: bridge

